env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:prettier/recommended'
  - 'eslint:recommended'
plugins:
  - 'prettier'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  prettier/prettier: error
  indent:
    - error
    - 2
    - "SwitchCase": 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
